version: "3.8"

services:
  # --- MySQL (relacional) ---
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: cursos
      MYSQL_USER: cursos_user
      MYSQL_PASSWORD: cursos_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot1234"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [app-network]

  # --- MongoDB (documental) ---
  mongo:
    image: mongo:7
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root1234
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--username", "root", "--password", "root1234", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [app-network]

  # --- QA ---
  tp2-app-qa:
    image: soficuozzo/tp2-app:v1.1
    container_name: tp2-app-qa
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_healthy
    environment:
      APP_ENV: qa
      LOG_LEVEL: debug
      PORT: "8082"
      # MySQL
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_NAME: cursos_qa
      DB_USER: cursos_user
      DB_PASSWORD: cursos_pass
      # Mongo
      MONGO_HOST: mongo
      MONGO_PORT: "27017"
      MONGO_USER: root
      MONGO_PASSWORD: root1234
      MONGO_DB: cursosdb_qa
    ports:
      - "8082:8082"   # QA visible en localhost:8082
    networks: [app-network]
    restart: on-failure

  # --- PROD ---
  tp2-app-prod:
    image: soficuozzo/tp2-app:v1.1
    container_name: tp2-app-prod
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_healthy
    environment:
      APP_ENV: prod
      LOG_LEVEL: error
      PORT: "8082"
      # MySQL
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_NAME: cursos_prod
      DB_USER: cursos_user
      DB_PASSWORD: cursos_pass
      # Mongo
      MONGO_HOST: mongo
      MONGO_PORT: "27017"
      MONGO_USER: root
      MONGO_PASSWORD: root1234
      MONGO_DB: cursosdb_prod
    ports:
      - "8089:8082"   # PROD visible en localhost:8089
    networks: [app-network]
    restart: on-failure

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  mongo-data:
